### ISSUE TITLE
Using bottlejack with other CMS

### ISSUE THREAD

**Issue by WillJarrettData** [jsoma/bottlejack#10]
It would be great to use bottlejack in conjunction with a commerical CMS like WordPress.

I like the control you get with bottlejack and how fast it is to go from offline draft to webpage, but I don't want to abandon the work I put into my WordPress portfolio site. Is it possible to integrate pages built with bottlejack into an existing WordPress site? If so, I'd love to see a tutorial on how that could be done.

**Comment by jsoma** [comment]
Unfortunately since WordPress is a beast unto itself, I think your best bet is to Google your way to a solution to "hosting individual HTML pages through WordPress" and just upload the whole shebang. Alternatively, you could edit your bottlejack templates to output raw HTML without `<head>` or `<body>` tags, nor classes/ids, and then paste the content right into the WP editor.

If you figure it out and make a tutorial I'm happy to include it, though!
